#!/bin/bash

echo "Starting Kubernetes cluster using Minikube..."

if minikube status | grep -q "host: Running"; then
    echo "✅ Minikube is already running!"
else
    minikube start --driver=docker
fi

# Checking if Minikube started
if [ $? -ne 0 ]; then
	echo "Failed to start Minikube Cluster."
	exit 1
fi

echo "Minikube started successfully!"
echo "Checking cluster info..."

kubectl cluster-info

if [ $? -ne 0 ]; then
	echo "Failed to retrieve cluster info."
	exit 1
fi

echo "Checking on node status..."
kubectl get nodes

# Listing all pods
echo "Listing all pods in all namespaces..."
kubectl get pods --all-namespaces

echo "Kubernetes local cluster setup complete!"
